/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 29/06/2023 11:55:03
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLDSIFreq_Value                     500000000
#define MX_SYSCLKFreq_VALUE                     480000000
#define MX_HCLKFreq_Value                       240000000
#define MX_CortexFreq_Value                     480000000
#define MX_APB1Freq_Value                       120000000
#define MX_APB2Freq_Value                       120000000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        480000000
#define MX_WatchDogFreq_Value                   32000
#define MX_DSIFreq_Value                        96000000
#define MX_DSIPHYCLKFreq_Value                  96000000
#define MX_DSITXEscFreq_Value                   20000000
#define MX_SPDIFRXFreq_Value                    480000000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_MCO2PinFreq_Value                    480000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- QUADSPI    --------------------------------*/

#define MX_QUADSPI                              1

/* GPIO Configuration */

/* Pin PB2 */
#define MX_QUADSPI_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_CLK_Pin                      PB2
#define MX_QUADSPI_CLK_GPIOx                    GPIOB
#define MX_QUADSPI_CLK_GPIO_PuPd                GPIO_PULLUP
#define MX_QUADSPI_CLK_GPIO_Pin                 GPIO_PIN_2
#define MX_QUADSPI_CLK_GPIO_AF                  GPIO_AF9_QUADSPI
#define MX_QUADSPI_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PB6 */
#define MX_QUADSPI_BK1_NCS_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_NCS_GPIO_FM6             __NULL
#define MX_QUADSPI_BK1_NCS_Pin                  PB6
#define MX_QUADSPI_BK1_NCS_GPIOx                GPIOB
#define MX_QUADSPI_BK1_NCS_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_NCS_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_NCS_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_NCS_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF6 */
#define MX_QUADSPI_BK1_IO3_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO3_Pin                  PF6
#define MX_QUADSPI_BK1_IO3_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO3_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_IO3_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_IO3_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO3_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF7 */
#define MX_QUADSPI_BK1_IO2_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO2_Pin                  PF7
#define MX_QUADSPI_BK1_IO2_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO2_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_IO2_GPIO_Pin             GPIO_PIN_7
#define MX_QUADSPI_BK1_IO2_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO2_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_QUADSPI_BK1_IO1_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO1_Pin                  PF9
#define MX_QUADSPI_BK1_IO1_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO1_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_IO1_GPIO_Pin             GPIO_PIN_9
#define MX_QUADSPI_BK1_IO1_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO1_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF8 */
#define MX_QUADSPI_BK1_IO0_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO0_Pin                  PF8
#define MX_QUADSPI_BK1_IO0_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO0_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_IO0_GPIO_Pin             GPIO_PIN_8
#define MX_QUADSPI_BK1_IO0_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO0_GPIO_Mode            GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

